server:
  port: 8080

database:
  name: sensitive_demo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

sensitive-demo:
  sensitive:
    enable: true
    deny: 脏话
    allow:

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true